config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root to: "dashboard#index"
  resources :users
  resources :teams
  resources :roles
  resources :activate_teams, only: [:show]
  resources :profile, only: [:index, :update]
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthenticatedTeamController
  before_action :authenticate_user!
  skip_before_action :authenticate_team!

  def index
    @owners = User.owners.decorate
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def authorize_link_to(action_name, resource, permission, path, **options)
    return unless policy(resource).send(permission)
    link_to action_name, path, options
  end
end

app/views/dashboard/_owners_table.html.haml
.relative.overflow-x-auto
  %table.border.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400
    %thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-blue-700.dark:text-gray-400
      %tr
        %th.px-6.py-3{scope: "col"}
          Full name
        %th.px-6.py-3{scope: "col"}
          email
        %th.px-6.py-3{scope: "col"}
          default password
    %tbody
      - @owners.each do |owner|
        %tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700
          %td.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{scope: "row"}
            = owner.full_name
          %td.px-6.py-4
            = owner.email
          %td.px-6.py-4
            password

app/views/dashboard/index.html.haml
.grid.grid-cols-3.gap-4.mb-4
  .flex.items-center.justify-center.h-24.rounded.bg-gray-50.dark:bg-gray-800
    = link_to "New team", new_team_path, class: "text-2xl text-blue-500 dark:text-blue-700"
  .flex.items-center.justify-center.h-24.rounded.bg-gray-50.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.h-24.rounded.bg-gray-50.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
.mb-4.p-10.rounded.bg-gray-50.dark:bg-gray-800
  %p.text-2xl List of users who are owners of teams
  = render partial: "owners_table"
.grid.grid-cols-2.gap-4.mb-4
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
.flex.items-center.justify-center.h-48.mb-4.rounded.bg-gray-50.dark:bg-gray-800
  %p.text-2xl.text-gray-400.dark:text-gray-500
    %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
      %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
.grid.grid-cols-2.gap-4
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-80
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
  .flex.items-center.justify-center.rounded.bg-gray-50.h-28.dark:bg-gray-800
    %p.text-2xl.text-gray-400.dark:text-gray-500
      %svg{"aria-hidden" => "true", :class => "w-3.5 h-3.5", :fill => "none", :viewbox => "0 0 18 18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M9 1v16M1 9h16", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}