config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root to: "dashboard#index"
  resources :users
  resources :teams
  resources :roles
  resources :activate_teams, only: [:show]
  resources :profile, only: [:index, :update]
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :team_roles, dependent: :destroy
  belongs_to :team, optional: true
end

app/controllers/roles_controller.rb
class RolesController < AuthenticatedTeamController
  before_action :set_role, only: [:edit, :update, :destroy]

  def index
    authorize :role, :index?
    @roles = current_team.roles.order(id: :asc).decorate
  end

  def new
    authorize :role, :create?
    @role = current_team.own_roles.new(permissions: {})
    @resources = RoleResource.all
  end

  def create
    authorize :role, :create?
    service = Roles::CreateTeamRoleService.call(current_team, permitted_params)
    if service.success?
      redirect_to edit_role_path(service.result), notice: "Role created successfully"
    else
      flash[:error] = service.errors.full_messages.join(", ")
      redirect_back fallback_location: new_role_path, flash: flash
    end
  end

  def edit
    authorize :role, :edit?
    @resources = RoleResource.all
  end

  def update
    authorize :role, :update?
    if @role.update(permitted_params)
      redirect_to edit_role_path(@role), notice: "Role updated successfully"
    else
      flash[:error] = @role.errors.full_messages.join(", ")
      redirect_back fallback_location: edit_role_path(@role), flash: flash
    end
  end

  def destroy
    authorize :role, :destroy?
    @role.destroy
    redirect_to roles_path
  end

  private

  def permitted_params
    params.require(:role).permit(:name, :description, permissions: {})
  end

  def set_role
    @role = current_team.roles.find(params[:id]).decorate
  end

  def pundit_user
    PunditUserRoleContext.new(current_user, current_team, @role)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
  def permission_checkbox_tag(role, resource_name, action_value)
    checked = role.permissions[resource_name]&.include?(action_value.to_s)
    check_box_tag "role[permissions][#{resource_name}][]", action_value, checked, class: permission_checkbox_css, id: "#{resource_name}_#{action_value}",
      data: {target: "role.checkbox", action: "input->role#toggle"}
  end

  private

  def permission_checkbox_css
    %w[
      w-4
      h-4
      text-blue-600
      bg-gray-100
      border-gray-300
      rounded
      focus:ring-blue-500
      dark:focus:ring-blue-600
      dark:ring-offset-gray-800
      focus:ring-2
      dark:bg-gray-700
      dark:border-gray-600
    ].join(" ")
  end
end

app/views/roles/_permissions.html.haml
.relative.overflow-x-auto
  %table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400{ "data-controller" => "role"}
    %thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
      %tr
        %th.px-6.py-3{scope: "col"}
        - @resources.each do |role_resource|
          %th.text-center.px-6.py-3{scope: "col"}
            = role_resource["name"]
    %tbody
      - RoleResource::ACTIONS.each do |action_name, action_value|
        %tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700
          %th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{scope: "row"}
            = action_name
          - @resources.each do |resc|
            %td.text-center.px-6.py-4
              = permission_checkbox_tag @role, resc["name"], action_value

app/views/roles/_role.html.haml
%tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700
  %th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{:scope => "row", "data-role-id-param" => "#{role.id}", "data-action" => "click->role#navigate"}
    = role.id
  %td.px-6.py-4
    = role.name
  %td.px-6.py-4
    = role.role_type
  %td.px-6.py-4
    = role.description
  %td.px-6.py-4
    = role.permissions

app/views/roles/_roles.html.haml
.relative.overflow-x-auto
  %table.w-full.text-sm.text-left.rtl:text-right.text-gray-500.dark:text-gray-400{ "data-controller" => "role" }
    %thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
      %tr
        %th.px-6.py-3{:scope => "col"}
          ID
        %th.px-6.py-3{:scope => "col"}
          Name
        %th.px-6.py-3{:scope => "col"}
          Type
        %th.px-6.py-3{:scope => "col"}
          Description
        %th.px-6.py-3{:scope => "col"}
          Permissions
    %tbody
      = render partial: "role", collection: @roles

app/views/roles/edit.html.haml
%section.bg-white.dark:bg-gray-900{:data => {"controller" => "role"}}
  .max-w-2xl.px-4.py-8.mx-auto.lg:py-16
    %h2.mb-4.text-xl.font-bold.text-gray-900.dark:text-white
      = "Edit role: #{@role.name}"
    = form_with model: @role, url: role_path(@role), method: :patch, builder: TailwindFormBuilder do |f|
      .grid.gap-4.mb-4.sm:grid-cols-1.sm:gap-6.sm:mb-5
        .w-full
          %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "name"}
            Role name
          = f.text_field :name, class: "p-2.5", required: "required", placeholder: "Super admin"
        .w-full
          %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "description"}
            Description
          = f.text_field :description, class: "p-2.5"
        %div
          %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "user_ids"}
            Permissions
          = render partial: "permissions", locals: { f: f }
          -# %select#category{:class => "p-2.5", :multiple => "true"}
          -# = f.select :user_ids, @users.map { |user| [user.full_name, user.id] }, {}, { class: "p-2.5", multiple: true }
      .flex.items-center.space-x-4
        = f.authorize_submit :role, :update?, "Update", class: "py-2.5"
        = f.authorize_link_to "javascript:void(0)", :role, :destroy?, {:class => "py-2.5 flex", data: {action: "click->role#delete"}} do
          %svg.w-5.h-5.mr-1.-ml-1{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
            %path{"clip-rule" => "evenodd", :d => "M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z", "fill-rule" => "evenodd"}
          Delete
    = button_to "Delete", role_path(@role), method: :delete, data: { confirm: "Are you sure?", "role-target" => "deleteButton" }, class: "py-2.5 hidden"

app/views/roles/index.html.haml
.flex.mb-4
  = authorize_link_to "New role", :role, :create?, new_role_path, class: "py-2.5"
.flex.mb-4.rounded.bg-gray-50.dark:bg-gray-800
  = render partial: "roles"

app/views/roles/new.html.haml
%section.bg-white.dark:bg-gray-900
  .max-w-2xl.px-4.py-8.mx-auto.lg:py-16
    %h2.mb-4.text-xl.font-bold.text-gray-900.dark:text-white
      = "New role"
    = form_with model: @role, url: roles_path, method: :post, builder: TailwindFormBuilder do |f|
      .grid.gap-4.mb-4.sm:grid-cols-1.sm:gap-6.sm:mb-5
        .w-full
          %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "name"}
            Role name
          = f.text_field :name, class: "p-2.5", required: "required", placeholder: "Super admin"
        .w-full
          %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "description"}
            Description
          = f.text_field :description, class: "p-2.5"
        %div
          %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "user_ids"}
            Permissions
          = render partial: "permissions", locals: { f: f }
      .flex.items-center.space-x-4
        = f.submit "Create", class: "py-2.5"